Add web service to enable download of model file
jandraor/PANDEM_simulator pull request #2
Opened 2022-03-09 11:23 UTC by CJCGreen

The web service named 'model' allows download of the Stella model file (.stmx), which is in XMILE (XML) format. It assumes that the model file will be contained within a folder with the same name, eg model_01/model_01.stmx.

2022-03-09 16:35 UTC, jandraor requested changes

2022-03-09 16:35 UTC, jandraor commented on package/R/REST_framework.R
> +      model_file_contents = read_file(filename)
model_file_contents <- readr::read_file(filename)

2022-03-09 16:35 UTC, jandraor commented on package/R/REST_framework.R
> +      as_attachment(model_file_contents, filename)
plumber::as_attachment(model_file_contents, filename)

2022-03-09 16:35 UTC, jandraor commented on package/R/REST_framework.R
> +  if (!str_detect(filename, "\\.")) {
if (!stringr::str_detect(filename, "\\.")) {

2022-03-09 16:37 UTC, CJCGreen commented on package/R/REST_framework.R
> +      as_attachment(model_file_contents, filename)
ok

2022-03-09 16:38 UTC, CJCGreen commented on package/R/REST_framework.R
> +      as_attachment(model_file_contents, filename)
ok

2022-03-09 16:38 UTC, CJCGreen commented on package/R/REST_framework.R
> +  if (!str_detect(filename, "\\.")) {
ok

2022-03-10 11:41 UTC, CJCGreen commented on package/R/REST_framework.R
> +  if (!str_detect(filename, "\\.")) {
Hi Jair, there was a missing backslash in your suggestion, this is the correct line:
if (!stringr::str_detect(filename, "\\.")) {

2022-03-10 11:42 UTC, CJCGreen commented on package/R/REST_framework.R
> +      as_attachment(model_file_contents, filename)
Using the package as prefix with the :: operator is a great improvement, thank you for the suggestions!

2022-03-10 15:23 UTC, closed without merging

2022-03-10 15:24 UTC, jandraor commented
Fixed with #3